/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedOrganizationSlugProjectsIndexRouteImport } from './routes/_protected/$organizationSlug/projects/index'
import { Route as ProtectedOrganizationSlugProjectsProjectSlugRouteImport } from './routes/_protected/$organizationSlug/projects/$projectSlug'
import { Route as ProtectedOrganizationSlugProjectsProjectSlugBranchesIndexRouteImport } from './routes/_protected/$organizationSlug/projects/$projectSlug/branches/index'
import { Route as ProtectedOrganizationSlugProjectsProjectSlugBranchesBranchIdViewRouteImport } from './routes/_protected/$organizationSlug/projects/$projectSlug/branches/$branchId/$view'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOrganizationSlugProjectsIndexRoute =
  ProtectedOrganizationSlugProjectsIndexRouteImport.update({
    id: '/$organizationSlug/projects/',
    path: '/$organizationSlug/projects/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOrganizationSlugProjectsProjectSlugRoute =
  ProtectedOrganizationSlugProjectsProjectSlugRouteImport.update({
    id: '/$organizationSlug/projects/$projectSlug',
    path: '/$organizationSlug/projects/$projectSlug',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOrganizationSlugProjectsProjectSlugBranchesIndexRoute =
  ProtectedOrganizationSlugProjectsProjectSlugBranchesIndexRouteImport.update({
    id: '/branches/',
    path: '/branches/',
    getParentRoute: () => ProtectedOrganizationSlugProjectsProjectSlugRoute,
  } as any)
const ProtectedOrganizationSlugProjectsProjectSlugBranchesBranchIdViewRoute =
  ProtectedOrganizationSlugProjectsProjectSlugBranchesBranchIdViewRouteImport.update(
    {
      id: '/branches/$branchId/$view',
      path: '/branches/$branchId/$view',
      getParentRoute: () => ProtectedOrganizationSlugProjectsProjectSlugRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$organizationSlug/projects/$projectSlug': typeof ProtectedOrganizationSlugProjectsProjectSlugRouteWithChildren
  '/$organizationSlug/projects/': typeof ProtectedOrganizationSlugProjectsIndexRoute
  '/$organizationSlug/projects/$projectSlug/branches/': typeof ProtectedOrganizationSlugProjectsProjectSlugBranchesIndexRoute
  '/$organizationSlug/projects/$projectSlug/branches/$branchId/$view': typeof ProtectedOrganizationSlugProjectsProjectSlugBranchesBranchIdViewRoute
}
export interface FileRoutesByTo {
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/': typeof ProtectedIndexRoute
  '/$organizationSlug/projects/$projectSlug': typeof ProtectedOrganizationSlugProjectsProjectSlugRouteWithChildren
  '/$organizationSlug/projects': typeof ProtectedOrganizationSlugProjectsIndexRoute
  '/$organizationSlug/projects/$projectSlug/branches': typeof ProtectedOrganizationSlugProjectsProjectSlugBranchesIndexRoute
  '/$organizationSlug/projects/$projectSlug/branches/$branchId/$view': typeof ProtectedOrganizationSlugProjectsProjectSlugBranchesBranchIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/$organizationSlug/projects/$projectSlug': typeof ProtectedOrganizationSlugProjectsProjectSlugRouteWithChildren
  '/_protected/$organizationSlug/projects/': typeof ProtectedOrganizationSlugProjectsIndexRoute
  '/_protected/$organizationSlug/projects/$projectSlug/branches/': typeof ProtectedOrganizationSlugProjectsProjectSlugBranchesIndexRoute
  '/_protected/$organizationSlug/projects/$projectSlug/branches/$branchId/$view': typeof ProtectedOrganizationSlugProjectsProjectSlugBranchesBranchIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/signup'
    | '/$organizationSlug/projects/$projectSlug'
    | '/$organizationSlug/projects/'
    | '/$organizationSlug/projects/$projectSlug/branches/'
    | '/$organizationSlug/projects/$projectSlug/branches/$branchId/$view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home'
    | '/login'
    | '/signup'
    | '/'
    | '/$organizationSlug/projects/$projectSlug'
    | '/$organizationSlug/projects'
    | '/$organizationSlug/projects/$projectSlug/branches'
    | '/$organizationSlug/projects/$projectSlug/branches/$branchId/$view'
  id:
    | '__root__'
    | '/_protected'
    | '/home'
    | '/login'
    | '/signup'
    | '/_protected/'
    | '/_protected/$organizationSlug/projects/$projectSlug'
    | '/_protected/$organizationSlug/projects/'
    | '/_protected/$organizationSlug/projects/$projectSlug/branches/'
    | '/_protected/$organizationSlug/projects/$projectSlug/branches/$branchId/$view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/$organizationSlug/projects/': {
      id: '/_protected/$organizationSlug/projects/'
      path: '/$organizationSlug/projects'
      fullPath: '/$organizationSlug/projects/'
      preLoaderRoute: typeof ProtectedOrganizationSlugProjectsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/$organizationSlug/projects/$projectSlug': {
      id: '/_protected/$organizationSlug/projects/$projectSlug'
      path: '/$organizationSlug/projects/$projectSlug'
      fullPath: '/$organizationSlug/projects/$projectSlug'
      preLoaderRoute: typeof ProtectedOrganizationSlugProjectsProjectSlugRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/$organizationSlug/projects/$projectSlug/branches/': {
      id: '/_protected/$organizationSlug/projects/$projectSlug/branches/'
      path: '/branches'
      fullPath: '/$organizationSlug/projects/$projectSlug/branches/'
      preLoaderRoute: typeof ProtectedOrganizationSlugProjectsProjectSlugBranchesIndexRouteImport
      parentRoute: typeof ProtectedOrganizationSlugProjectsProjectSlugRoute
    }
    '/_protected/$organizationSlug/projects/$projectSlug/branches/$branchId/$view': {
      id: '/_protected/$organizationSlug/projects/$projectSlug/branches/$branchId/$view'
      path: '/branches/$branchId/$view'
      fullPath: '/$organizationSlug/projects/$projectSlug/branches/$branchId/$view'
      preLoaderRoute: typeof ProtectedOrganizationSlugProjectsProjectSlugBranchesBranchIdViewRouteImport
      parentRoute: typeof ProtectedOrganizationSlugProjectsProjectSlugRoute
    }
  }
}

interface ProtectedOrganizationSlugProjectsProjectSlugRouteChildren {
  ProtectedOrganizationSlugProjectsProjectSlugBranchesIndexRoute: typeof ProtectedOrganizationSlugProjectsProjectSlugBranchesIndexRoute
  ProtectedOrganizationSlugProjectsProjectSlugBranchesBranchIdViewRoute: typeof ProtectedOrganizationSlugProjectsProjectSlugBranchesBranchIdViewRoute
}

const ProtectedOrganizationSlugProjectsProjectSlugRouteChildren: ProtectedOrganizationSlugProjectsProjectSlugRouteChildren =
  {
    ProtectedOrganizationSlugProjectsProjectSlugBranchesIndexRoute:
      ProtectedOrganizationSlugProjectsProjectSlugBranchesIndexRoute,
    ProtectedOrganizationSlugProjectsProjectSlugBranchesBranchIdViewRoute:
      ProtectedOrganizationSlugProjectsProjectSlugBranchesBranchIdViewRoute,
  }

const ProtectedOrganizationSlugProjectsProjectSlugRouteWithChildren =
  ProtectedOrganizationSlugProjectsProjectSlugRoute._addFileChildren(
    ProtectedOrganizationSlugProjectsProjectSlugRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedOrganizationSlugProjectsProjectSlugRoute: typeof ProtectedOrganizationSlugProjectsProjectSlugRouteWithChildren
  ProtectedOrganizationSlugProjectsIndexRoute: typeof ProtectedOrganizationSlugProjectsIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedOrganizationSlugProjectsProjectSlugRoute:
    ProtectedOrganizationSlugProjectsProjectSlugRouteWithChildren,
  ProtectedOrganizationSlugProjectsIndexRoute:
    ProtectedOrganizationSlugProjectsIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
