import { access, chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  normalizeServerDomainHost,
  type ServerDomainCertificateType,
} from "@openbika/contracts";
import type { ApiEnv } from "@openbika/env";

const repoRoot = fileURLToPath(new URL("../../..", import.meta.url));
const defaultDynamicDir = join(repoRoot, "infra/docker/traefik/dynamic");
const defaultTemplatePath = join(
  defaultDynamicDir,
  "openbika-control-plane.yml.template",
);
const defaultComposeEnvPath = join(repoRoot, "infra/docker/.env");

interface ApplyServerDomainSettingsInput {
  certificateType: ServerDomainCertificateType;
  env: ApiEnv;
  host: string | null;
  https: boolean;
  letsEncryptEmail: string | null;
}

function apiUpstream(env: ApiEnv): string {
  return process.env.OPENBIKA_API_UPSTREAM?.trim() || env.API_PUBLIC_URL;
}

function dashboardUpstream(env: ApiEnv): string {
  return (
    process.env.OPENBIKA_DASHBOARD_UPSTREAM?.trim() ||
    process.env.DASHBOARD_PUBLIC_URL?.trim() ||
    "http://host.docker.internal:3000"
  );
}

function dynamicDir(env: ApiEnv): string {
  return env.OPENBIKA_TRAEFIK_DYNAMIC_DIR?.trim() || defaultDynamicDir;
}

function composeEnvPath(env: ApiEnv): string {
  return env.OPENBIKA_TRAEFIK_COMPOSE_ENV?.trim() || defaultComposeEnvPath;
}

function mainTraefikConfigPath(env: ApiEnv): string | null {
  return env.OPENBIKA_TRAEFIK_MAIN_CONFIG?.trim() || null;
}

function escapeYamlDoubleQuoted(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function renderHttpOnlyConfig({
  apiUrl,
  dashboardUrl,
  host,
}: {
  apiUrl: string;
  dashboardUrl: string;
  host: string;
}): string {
  const ruleHost = escapeYamlDoubleQuoted(host);
  const api = escapeYamlDoubleQuoted(apiUrl);
  const dashboard = escapeYamlDoubleQuoted(dashboardUrl);
  return `# Generated by OpenBika server domain settings.
http:
  routers:
    openbika-api:
      rule: "Host(\`${ruleHost}\`) && (PathPrefix(\`/api\`) || PathPrefix(\`/v1\`) || Path(\`/health\`) || Path(\`/openapi.json\`))"
      entryPoints:
        - web
      service: openbika-api
      priority: 20

    openbika-dashboard:
      rule: "Host(\`${ruleHost}\`)"
      entryPoints:
        - web
      service: openbika-dashboard
      priority: 10

  services:
    openbika-api:
      loadBalancer:
        servers:
          - url: "${api}"

    openbika-dashboard:
      loadBalancer:
        servers:
          - url: "${dashboard}"
`;
}

async function renderHttpsConfig({
  apiUrl,
  dashboardUrl,
  host,
}: {
  apiUrl: string;
  dashboardUrl: string;
  host: string;
}): Promise<string> {
  const template = await readFile(defaultTemplatePath, "utf8");
  return template
    .replaceAll("__OPENBIKA_PUBLIC_HOST__", host)
    .replaceAll("__OPENBIKA_API_UPSTREAM__", apiUrl)
    .replaceAll("__OPENBIKA_DASHBOARD_UPSTREAM__", dashboardUrl)
    .replace(
      "# Rendered to openbika-control-plane.yml by scripts/install.sh (see traefik/README.md).",
      "# Generated by OpenBika server domain settings.",
    );
}

function renderDisabledConfig(): string {
  return `# Generated by OpenBika server domain settings.
http:
  routers: {}
  services: {}
`;
}

async function ensureAcmeStorage(dir: string): Promise<void> {
  const acmePath = join(dir, "acme.json");
  try {
    await access(acmePath);
  } catch {
    await writeFile(acmePath, "", { flag: "wx" }).catch((error: unknown) => {
      if (
        error &&
        typeof error === "object" &&
        "code" in error &&
        error.code === "EEXIST"
      ) {
        return;
      }
      throw error;
    });
  }
  await chmod(acmePath, 0o600).catch(() => undefined);
}

async function updateComposeAcmeEmail(path: string, email: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  let current = "";
  try {
    current = await readFile(path, "utf8");
  } catch {
    current = "";
  }

  const line = `OPENBIKA_TRAEFIK_ACME_EMAIL=${email}`;
  const next = current.match(/^OPENBIKA_TRAEFIK_ACME_EMAIL=.*$/m)
    ? current.replace(/^OPENBIKA_TRAEFIK_ACME_EMAIL=.*$/m, line)
    : `${current.trimEnd()}${current.trimEnd() ? "\n" : ""}${line}\n`;

  await writeFile(path, next, "utf8");
}

async function updateMainTraefikEmail(
  path: string | null,
  email: string,
): Promise<void> {
  if (!path) return;
  const current = await readFile(path, "utf8");
  const next = current.match(/(^\s*email:\s*).+$/m)
    ? current.replace(/(^\s*email:\s*).+$/m, (_match, prefix: string) => {
        return `${prefix}${email}`;
      })
    : current;
  await writeFile(path, next, "utf8");
}

export async function applyServerDomainSettings({
  certificateType,
  env,
  host,
  https,
  letsEncryptEmail,
}: ApplyServerDomainSettingsInput): Promise<void> {
  const dir = dynamicDir(env);
  await mkdir(dir, { recursive: true });

  const normalizedHost = host ? normalizeServerDomainHost(host) : null;
  const apiUrl = apiUpstream(env);
  const dashboardUrl = dashboardUpstream(env);
  const config =
    normalizedHost === null
      ? renderDisabledConfig()
      : https && certificateType === "letsencrypt"
        ? await renderHttpsConfig({
            apiUrl,
            dashboardUrl,
            host: normalizedHost,
          })
        : renderHttpOnlyConfig({
            apiUrl,
            dashboardUrl,
            host: normalizedHost,
          });

  await writeFile(join(dir, "openbika-control-plane.yml"), config, "utf8");

  if (https && certificateType === "letsencrypt") {
    await ensureAcmeStorage(dir);
    if (letsEncryptEmail) {
      await updateComposeAcmeEmail(composeEnvPath(env), letsEncryptEmail);
      await updateMainTraefikEmail(mainTraefikConfigPath(env), letsEncryptEmail);
    }
  }
}
